### ISSUE TITLE
docker-compose: No such file or directory

### ISSUE THREAD

**Issue by eoan-ermine** [userver-framework/service_template#49]
```shell
eoanermine@eoanermine:~/Repositories/userver_sample$ make docker-start-service-release
make: docker-compose: No such file or directory
make: *** [Makefile:86: docker-start-service-release] Error 127
```

**Comment by apolukhin** [comment]
Ubuntu 20.04 still uses `docker-compose`, we can not switch to `docker compose`

Instead, we provided a customization of the command in https://github.com/userver-framework/service_template/commit/a095049c8a0c9ac747a5fb02a600c31299757035
