### ISSUE TITLE
make docker-start-service-release error

### ISSUE THREAD

**Issue by mchernov-intel** [userver-framework/service_template#55]
OS: Ubuntu 22
![image](https://github.com/userver-framework/service_template/assets/55237517/6923d738-6069-4949-9074-141b0fb8e8dd)

'''
Unhandled exception in components::Run: Error while parsing configs from file '/home/user/.local/etc/service_template/static_config.yaml'. Details: Field 'components_manager.task_processors.main-task-processor.worker_threads' is missing
make: *** [Makefile:81: --in-docker-start-release] Error 1
make: *** [Makefile:88: docker-start-service-release] Error 2
'''

**Comment by Rephobia** [comment]
@mchernov-intel I had the same issue. I assume this commit https://github.com/userver-framework/service_template/commit/e0bdb1305ef0bb195e5c6eddb81dc87ca040d280 fixed it

**Comment by apolukhin** [comment]
Looks like it was fixed in https://github.com/userver-framework/service_template/commit/e0bdb1305ef0bb195e5c6eddb81dc87ca040d280 . Please reopen if not

Many thanks for the bug repprt!
